- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-json
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: flake8
      args: [--max-line-length=99]
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: git://github.com/asottile/reorder_python_imports
  sha: v0.2.0
  hooks:
    - id: reorder-python-imports
      language_version: 'python2.7'
      exclude: 'setup\.py'
      args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
